// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msgs.proto

package msgs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ORMVersionFieldProto struct {
	VersionBytes         []byte   `protobuf:"bytes,1,opt,name=version_bytes,json=versionBytes,proto3" json:"version_bytes,omitempty"`
	Metadata             []byte   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ORMVersionFieldProto) Reset()         { *m = ORMVersionFieldProto{} }
func (m *ORMVersionFieldProto) String() string { return proto.CompactTextString(m) }
func (*ORMVersionFieldProto) ProtoMessage()    {}
func (*ORMVersionFieldProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_952909143bb80d72, []int{0}
}

func (m *ORMVersionFieldProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ORMVersionFieldProto.Unmarshal(m, b)
}
func (m *ORMVersionFieldProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ORMVersionFieldProto.Marshal(b, m, deterministic)
}
func (m *ORMVersionFieldProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ORMVersionFieldProto.Merge(m, src)
}
func (m *ORMVersionFieldProto) XXX_Size() int {
	return xxx_messageInfo_ORMVersionFieldProto.Size(m)
}
func (m *ORMVersionFieldProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ORMVersionFieldProto.DiscardUnknown(m)
}

var xxx_messageInfo_ORMVersionFieldProto proto.InternalMessageInfo

func (m *ORMVersionFieldProto) GetVersionBytes() []byte {
	if m != nil {
		return m.VersionBytes
	}
	return nil
}

func (m *ORMVersionFieldProto) GetMetadata() []byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*ORMVersionFieldProto)(nil), "msgs.ORMVersionFieldProto")
}

func init() { proto.RegisterFile("msgs.proto", fileDescriptor_952909143bb80d72) }

var fileDescriptor_952909143bb80d72 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2d, 0x4e, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xc2, 0xb9, 0x44, 0xfc, 0x83,
	0x7c, 0xc3, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0xdc, 0x32, 0x53, 0x73, 0x52, 0x02, 0xc0, 0xb2,
	0xca, 0x5c, 0xbc, 0x65, 0x10, 0xc1, 0xf8, 0xa4, 0xca, 0x92, 0xd4, 0x62, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0x9e, 0x20, 0x1e, 0xa8, 0xa0, 0x13, 0x48, 0x4c, 0x48, 0x8a, 0x8b, 0x23, 0x37, 0xb5, 0x24,
	0x31, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x09, 0x2c, 0x0f, 0xe7, 0x3b, 0x05, 0x47, 0x05, 0xa6, 0x67,
	0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x67, 0x54, 0x16, 0xa4, 0x16, 0xe5, 0xa4,
	0xa6, 0xa4, 0xa7, 0x16, 0xe9, 0xa7, 0x25, 0x26, 0x15, 0x65, 0x26, 0xeb, 0x27, 0xe7, 0x17, 0xa5,
	0xea, 0x43, 0x85, 0xb2, 0xcb, 0xa0, 0x8c, 0x92, 0x8a, 0xdc, 0xf4, 0xdc, 0x12, 0xfd, 0xe2, 0x92,
	0xc4, 0x92, 0xd4, 0x94, 0x24, 0x08, 0x9d, 0x5f, 0x94, 0x9b, 0x92, 0xa4, 0x0f, 0x72, 0x6d, 0x12,
	0x1b, 0xd8, 0xe9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x23, 0xdf, 0x15, 0xc8, 0x00,
	0x00, 0x00,
}
