// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	protoutil "github.com/hyperledger/fabric/protoutil"
	mock "github.com/stretchr/testify/mock"
)

// PolicyEvaluator is an autogenerated mock type for the PolicyEvaluator type
type PolicyEvaluator struct {
	mock.Mock
}

// Evaluate provides a mock function with given fields: policyBytes, signatureSet, vrfSet
func (_m *PolicyEvaluator) Evaluate(policyBytes []byte, signatureSet []*protoutil.SignedData, vrfSet []*protoutil.VrfData) error {
	ret := _m.Called(policyBytes, signatureSet, vrfSet)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []*protoutil.SignedData, []*protoutil.VrfData) error); ok {
		r0 = rf(policyBytes, signatureSet, vrfSet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
